const List<String> locations = [
  "Beograd",
  "Novi Sad",
  "Niš",
  "Kragujevac",
  "Subotica",
  "Zrenjanin",
  "Pančevo",
  "Čačak",
  "Kraljevo",
  "Leskovac",
  "Smederevo",
  "Kruševac",
  "Valjevo",
  "Vranje",
  "Šabac",
  "Užice",
  "Zaječar",
  "Požarevac",
  "Sombor",
  "Jagodina",
];
const List<String> categories = [
  "Vodoinstalater",
  "Električar",
  "Moler",
  "Stolar",
  "Automehaničar",
  "Zidar",
  "Keramičar",
  "Teslar",
  "Bravar",
  "Zavarivač",
  "Gipsar",
  "Parketar",
  "Farbar",
  "Majstor za klima uređaje",
  "Monter PVC stolarije",
];
